# Generated by Django 5.0.3 on 2024-04-14 10:15

import django.core.validators
import django.db.models.deletion
import feedback.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "theme",
                    models.IntegerField(
                        choices=[
                            (1, "Учетная запись"),
                            (2, "Технические проблемы"),
                            (3, "Отзывы и предложения"),
                        ],
                        help_text="Выберите тему обращения",
                        verbose_name="тема обращения",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст обращения")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратные связи",
                "ordering": ("theme",),
            },
        ),
        migrations.CreateModel(
            name="FeedbackFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=feedback.models.item_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                        verbose_name="дополнительные файлы",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="feedback.feedback"
                    ),
                ),
            ],
        ),
    ]
