# Generated by Django 5.0.3 on 2024-04-15 13:17

import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackfiles",
            name="files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=feedback.models.item_directory_path,
                verbose_name="дополнительные файлы",
            ),
        ),
    ]
