# Generated by Django 5.0.3 on 2024-04-18 06:28

import django.utils.timezone
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackfiles",
            options={
                "verbose_name": "дополнительный файл",
                "verbose_name_plural": "дополнительные файлы",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="создано"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, verbose_name="изменено"),
        ),
        migrations.AlterField(
            model_name="feedbackfiles",
            name="files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=feedback.models.item_directory_path,
                verbose_name="дополнительные файлы",
            ),
        ),
    ]
