# Generated by Django 5.0.3 on 2024-04-16 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedbackfiles_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_on",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="создано"
            ),
            preserve_default=False,
        ),
    ]
