# Generated by Django 5.0.3 on 2024-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedbackfiles_options_feedback_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Создано"), (2, "В процессе"), (3, "Решено")],
                default=1,
                verbose_name="статус",
            ),
            preserve_default=False,
        ),
    ]
