stages:
  - linting
  - black

flake8:
  stage: linting
  image: python:3.10
  script:
    - pip install flake8 flake8-absolute-import flake8-commas flake8-import-order flake8-print flake8-quotes flake8-use-pathlib pep8-naming
    - flake8 --config .flake8

black:
  stage: black
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --config pyproject.toml --check .