# Generated by Django 5.0.3 on 2024-04-23 12:57

import django.db.models.deletion
import event.models
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="workuser",
            name="files",
        ),
        migrations.AddField(
            model_name="workuser",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                help_text="Загрузите вашу работу",
                null=True,
                upload_to=event.models.item_directory_path,
                verbose_name="работа",
            ),
        ),
        migrations.AlterField(
            model_name="voteevent",
            name="score",
            field=models.IntegerField(
                choices=[
                    (1, "Ужасно"),
                    (2, "Неплохо"),
                    (3, "Хорошо"),
                    (4, "Отлично"),
                    (5, "Восхитительно"),
                ],
                help_text="Выберите подходящую оценку для работы",
                verbose_name="оценка работы",
            ),
        ),
        migrations.AlterField(
            model_name="voteevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="workuser",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.event",
                verbose_name="Выберите конкурс",
            ),
        ),
        migrations.DeleteModel(
            name="UserEvent",
        ),
    ]
