# Generated by Django 5.0.3 on 2024-04-22 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_workuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteevent",
            name="score",
            field=models.IntegerField(
                choices=[
                    (1, "Ужасно"),
                    (2, "Неплохо"),
                    (3, "Хорошо"),
                    (4, "Отлично"),
                    (5, "Восхитительно"),
                ],
                help_text="Выберите подходящую оценку для работы",
                verbose_name="оценка работы",
            ),
        ),
        migrations.AlterField(
            model_name="workuser",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.event",
                verbose_name="Выберите конкурс",
            ),
        ),
        migrations.DeleteModel(
            name="UserEvent",
        ),
    ]
