# Generated by Django 5.0.3 on 2024-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaqQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="Введите частозадаваемый вопрос",
                        max_length=100,
                        verbose_name="вопрос",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Введите ответ на частозадаваемый вопрос (макс. 350 символов)",
                        max_length=350,
                        verbose_name="ответ на вопрос",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True, verbose_name="создано")),
            ],
            options={
                "verbose_name": "частозадаваемый вопрос",
                "verbose_name_plural": "частозадаваемые вопросы",
                "ordering": ("question",),
            },
        ),
    ]
