# Generated by Django 5.0.3 on 2024-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqquestions",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, verbose_name="изменено"),
        ),
        migrations.AlterField(
            model_name="faqquestions",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создано"),
        ),
    ]
