# Generated by Django 5.0.3 on 2024-04-15 13:53

import animals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя вашего питомца",
                        max_length=70,
                        verbose_name="имя питомца",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True,
                        help_text="Введите биографию вашего питомца",
                        max_length=1200,
                        null=True,
                        verbose_name="биография питомца",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату рождения вашего питомца",
                        null=True,
                        verbose_name="дата рождения",
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату смерти вашего питомца",
                        null=True,
                        verbose_name="дата смерти",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True, verbose_name="создано")),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение вашего питомца",
                        null=True,
                        upload_to=animals.models.item_directory_path,
                        verbose_name="Изображение питомца",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "питомец",
                "verbose_name_plural": "питомцы",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AnimalComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        help_text="Введите комментарий", max_length=200, verbose_name="комментарий"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animals.animal"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "files",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=animals.models.item_directory_path,
                        verbose_name="дополнительные изображения",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animal_images",
                        to="animals.animal",
                    ),
                ),
            ],
        ),
    ]
