# Generated by Django 5.0.3 on 2024-04-18 06:28

import animals.models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalcomments",
            options={
                "ordering": ("user",),
                "verbose_name": "комментарий",
                "verbose_name_plural": "комментарии",
            },
        ),
        migrations.AddField(
            model_name="animal",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, verbose_name="изменено"),
        ),
        migrations.AddField(
            model_name="animalcomments",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="создано"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animalcomments",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, verbose_name="изменено"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создано"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="main_image",
            field=sorl.thumbnail.fields.ImageField(
                default=django.utils.timezone.now,
                help_text="Загрузите изображение вашего питомца",
                upload_to=animals.models.item_directory_path,
                verbose_name="Изображение питомца",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="animalcomments",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animal_comments",
                to="animals.animal",
            ),
        ),
        migrations.AlterField(
            model_name="animalcomments",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="AnimalImages",
        ),
    ]
