# Generated by Django 5.0.3 on 2024-04-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_alter_animal_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalcomments",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animal_comments",
                to="animals.animal",
            ),
        ),
    ]
